image: python:3-slim

stages:
  - test
  - build
  - dist

cache:
  paths:
    - dist/

before_script:
  - python -V

job_test:
  stage: test
  script:
    - pip install -r requirements.txt
    - py.test tests/

job_build:
  stage: build
  script:
    - rm -rf dist/
    - python setup.py check sdist
    - ls -la dist/
  only:
    refs:
      - master
      - staging

job_dist:
  stage: dist
  script:
    - pip install twine
    - python -m twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*.tar.gz
  only:
    refs:
      - master
